#index:
#    path: /
#    controller: App\Controller\DefaultController::index

AO_Webshop:
    path: /ao-webshop
    controller: App\Controller\WebshopController::Welcome

AO_Webshop_Product:
    path: /ao-webshop/product
    controller: App\Controller\WebshopController::Product

AO_Webshop_Account:
    path: /ao-webshop/account
    controller: App\Controller\WebshopController::Account

# ------------------------------------------------------- Account -----------------------------------------------------------

AO_Webshop_Account_Register:
    path: /ao-webshop/account/register
    controller: App\Controller\UserController::Account_Register

AO_Webshop_Account_Login:
    path: /ao-webshop/account/login
    controller: App\Controller\UserController::Account_Login

AO_Webshop_Account_Logout:
    path: /ao-webshop/account/logout
    controller: App\Controller\WebshopController::Account_logout