#index:
#    path: /
#    controller: App\Controller\DefaultController::index

AO_Webshop:
    path: /ao-webshop
    controller: App\Controller\WebshopController::Welcome

AO_Webshop_Product:
    path: /ao-webshop/product
    controller: App\Controller\WebshopController::Product